### ISSUE TITLE
rolls back and fails

### ISSUE THREAD

**Issue by queglay** [aws-quickstart/quickstart-cloudvideoediting#1]
Running this stack to create a new vpc from scratch, the scripts don't work on AWS.  It fails and rolls back.

<img width="1334" alt="screen shot 2018-04-29 at 10 00 43 am" src="https://user-images.githubusercontent.com/4046493/39401235-cc980800-4b94-11e8-9e58-874e922b68ee.png">

**Comment by queglay** [comment]
I had an instance limit of 1 on that machine type for a while and have been able to use them successfully for normal use.

**Comment by zoomerkind** [comment]
Try spinning up again with the rollback set to false (see above) and we can look at the autoscaling group errors.

**Comment by queglay** [comment]
I disabled the roll back and have these two errors-
<img width="1442" alt="screen shot 2018-05-06 at 9 54 14 pm" src="https://user-images.githubusercontent.com/4046493/39672116-2455931c-5178-11e8-879a-be923859edce.png">
<img width="1435" alt="screen shot 2018-05-06 at 9 53 57 pm" src="https://user-images.githubusercontent.com/4046493/39672117-249edd24-5178-11e8-96c2-29a804b07a1e.png">

**Comment by zoomerkind** [comment]
That is the high level message from CloudFormation.  If you look at the AWS Console under EC2->Auto Scaling->Auto Scaling Groups and click the Activity History tab, you will be able to expand error messages there.

Please post those details and that should help us determine what is happening.

**Comment by queglay** [comment]
Thankyou!

It looks like the error was because I had never subscribed to the windows + nvidia GRID ami.  this should be added as an intitial step in the instructions.  I can understand how a developer would never encounter this while writing documentation, it would affect a first time user only.

Description:DescriptionLaunching a new EC2 instance. Status Reason: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit http://aws.amazon.com/marketplace/pp?sku=3ybncjerqbt57hm8g24nr1dqn. Launching EC2 instance failed.
--
Cause:CauseAt 2018-05-07T02:58:01Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 1.

**Comment by queglay** [comment]
When I tried to start from scratch again, it was complaining that a stack already exists, so I'm deleting it and trying to start again.

**Comment by queglay** [comment]
This worked and the stack completed.  Thankyou for your help on this issue!
